# /// script
# requires-python = ">=3.10"
# dependencies = ["numpy", "pillow>=10.4", "opencv-python-headless"]
# ///
"""Rebuild the private Mio project from three local PNGs and a tracked text recipe.

Run from the repository: uv run tools/rebuild-mio.py
No image is downloaded, generated by an external service, or added to Git.
"""

import argparse
import hashlib
import importlib.util
import json
import os
from pathlib import Path
import re
import shutil
import subprocess
import sys
import tempfile
import uuid

import cv2
import numpy as np
from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
RECIPE = ROOT / "configs" / "mio"
PARTS = ("back_hair", "body", "front_hair")


def load_tool(name):
    spec = importlib.util.spec_from_file_location(
        f"mio_{name.replace('-', '_')}", ROOT / "tools" / f"{name}.py"
    )
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def read_parts(input_dir, settings):
    expected = (settings["image"]["width"], settings["image"]["height"])
    parts = {}
    for name in PARTS:
        filename = settings["parts"][name]
        if Path(filename).name != filename or not filename.endswith(".png"):
            raise ValueError(f"Invalid input filename in recipe: {filename}")
        path = input_dir / filename
        if not path.is_file():
            raise ValueError(f"Missing {path}. Put all three original PNGs in {input_dir}.")
        with Image.open(path) as image:
            if image.format != "PNG" or image.size != expected:
                raise ValueError(f"{filename}: expected PNG {expected[0]} x {expected[1]}, got {image.format} {image.size}")
            if "A" not in image.getbands() and "transparency" not in image.info:
                raise ValueError(f"{filename}: original PNG transparency is required.")
            parts[name] = image.convert("RGBA")
    return parts


def composite_parts(parts, settings):
    if settings["compositeOrder"] != list(PARTS):
        raise ValueError("Mio composition must be back_hair, body, front_hair.")
    result = parts[PARTS[0]].copy()
    for name in PARTS[1:]:
        result = Image.alpha_composite(result, parts[name])
    return result


def exact_hair_mask(parts, settings):
    front = np.asarray(parts["front_hair"])[..., 3]
    back = np.asarray(parts["back_hair"])[..., 3]
    body = np.asarray(parts["body"])[..., 3]
    params = settings["hairMask"]
    occlusion = params["bodyOcclusionAlpha"]
    minimum = params["frontHairOnBodyMinAlpha"]
    if not 0 <= occlusion <= 255 or not 0 <= minimum <= 255:
        raise ValueError("Hair alpha thresholds must be between 0 and 255.")
    visible_front = np.where((body > occlusion) & (front < minimum), 0, front)
    mask = np.maximum(visible_front, np.where(body > occlusion, 0, back)).astype(np.uint8)
    # Keep the flower, star and blue ribbon attached to the head.
    polygon = np.asarray(params["headAccessoryPolygon"], dtype=float)
    if polygon.ndim != 2 or polygon.shape[1] != 2 or len(polygon) < 3 or not np.isfinite(polygon).all():
        raise ValueError("headAccessoryPolygon must contain at least three finite [x, y] points.")
    ornament = np.zeros(mask.shape, np.uint8)
    cv2.fillPoly(ornament, [np.rint(polygon).astype(np.int32)], 255)
    mask[ornament > 0] = 0
    return mask


def private_project(path):
    path = Path(path)
    if path.is_symlink():
        raise ValueError("Project output must not be a symlink.")
    path = path.resolve()
    projects = (ROOT / "projects").resolve()
    if path == projects or not path.is_relative_to(projects):
        raise ValueError("Project output must be a folder inside this repository's projects/.")
    if path.exists() and not path.is_dir():
        raise ValueError("Project output must be a directory.")
    if path.exists() and any(item.is_symlink() for item in path.rglob("*")):
        raise ValueError("Existing project contains symlinks; rebuild a separate folder.")
    return path


def prepare_tools(install):
    node = shutil.which("node")
    if not node:
        raise ValueError("Install Node.js 22.17+ and reopen your terminal.")
    version = subprocess.check_output([node, "--version"], text=True).strip()
    match = re.fullmatch(r"v(\d+)\.(\d+)\.(\d+)", version)
    if not match or tuple(map(int, match.groups())) < (22, 17, 0):
        raise ValueError(f"Node.js 22.17+ is required; found {version}.")
    if install and not (ROOT / "node_modules" / "vite" / "package.json").is_file():
        npm = shutil.which("npm")
        if not npm:
            raise ValueError("npm is required for first-time editor setup.")
        command = [npm, "ci"]
        if os.name == "nt":
            command = [os.environ.get("COMSPEC", "cmd.exe"), "/c", *command]
        subprocess.run(command, cwd=ROOT, check=True)
    return node


def validate_rig(node, path):
    subprocess.run([node, "--experimental-strip-types", str(ROOT / "tools/validate-rig.mjs"), str(path)], cwd=ROOT, check=True)


def publish_project(stage, project):
    """Replace a complete project only after all builds pass, rolling back rename failures."""
    backup = project.with_name(f".mio-backup-{uuid.uuid4().hex}")
    existed = project.exists()
    if existed:
        project.rename(backup)
    try:
        stage.rename(project)
    except OSError:
        if existed:
            backup.rename(project)
        raise
    if existed:
        try:
            shutil.rmtree(backup)
        except OSError:
            print(f"Rebuild succeeded; previous project backup remains at {backup}", file=sys.stderr)


def rebuild(project, input_dir=None, reset_rig=False, install=True):
    project = private_project(project)
    input_dir = Path(input_dir).resolve() if input_dir else project / "inputs/originals"
    settings = json.loads((RECIPE / "rebuild.json").read_text(encoding="utf-8"))
    parts = read_parts(input_dir, settings)
    source = composite_parts(parts, settings)
    # Refuse accidental replacement of a different or hand-edited source image.
    if (project / "source.png").exists():
        with Image.open(project / "source.png") as existing:
            if not np.array_equal(np.asarray(existing.convert("RGBA")), np.asarray(source)):
                raise ValueError("Existing source.png differs from the three PNG composite. Use a separate project folder to preserve it.")
    # Validate thresholds/ornament geometry before installing dependencies or writing output.
    hair = exact_hair_mask(parts, settings)
    node = prepare_tools(install)
    project.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(prefix=".mio-rebuild-", dir=project.parent) as temporary:
        stage = Path(temporary) / "project"
        if project.exists():
            shutil.copytree(project, stage)
        else:
            stage.mkdir()
        source.save(stage / "source.png")
        originals = stage / "inputs/originals"
        originals.mkdir(parents=True, exist_ok=True)
        for name in PARTS:
            filename = settings["parts"][name]
            shutil.copy2(input_dir / filename, originals / filename)
        if reset_rig or not (stage / "rig.draft.json").exists():
            shutil.copy2(RECIPE / "rig.draft.json", stage / "rig.draft.json")
        if reset_rig or not (stage / "rig.json").exists():
            shutil.copy2(RECIPE / "rig.json", stage / "rig.json")
        validate_rig(node, stage / "rig.draft.json")
        validate_rig(node, stage / "rig.json")
        builder = load_tool("build-layers")
        builder.hair_mask = lambda rgba, rig: hair.copy()
        builder.build(stage, stage / "rig.json")
        validate_rig(node, stage / "rig.json")
        # Changes to alpha-mask settings must invalidate the browser texture cache.
        manifest_path = stage / "built/layers.json"
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
        manifest["build"] = hashlib.sha256((manifest["build"] + json.dumps(settings, sort_keys=True)).encode() + Path(__file__).read_bytes()).hexdigest()[:12]
        manifest_path.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
        requests = load_tool("variant-requests")
        requests.generate(stage)
        variants = stage / "variants"
        sprites = load_tool("build-sprites")
        has_variants = any((variants / f"{name}.png").is_file() for name in (*sprites.EYE_VARIANTS, *sprites.MOUTH_VARIANTS))
        if has_variants:
            sprites.build(stage)
        publish_project(stage, project)
    print(f"Mio rebuilt: {project.relative_to(ROOT)}")
    print("Local PNGs and generated files remain under ignored projects/.")
    if not has_variants:
        if (project / "built/sprites/sprites.json").is_file():
            print("Existing local sprites were preserved. Their variant PNGs are needed to regenerate them.")
        else:
            print("No drawn variants supplied. The base avatar uses its local eye layers and procedural mouth.")
    print("No external image service was contacted.")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--project", type=Path, default=ROOT / "projects/mio", help="Output folder inside projects/ (default: projects/mio)")
    parser.add_argument("--input-dir", type=Path, help="Folder containing the three PNGs (default: output folder's inputs/originals)")
    parser.add_argument("--reset-rig", action="store_true", help="Restore tracked rig settings instead of preserving local edits")
    parser.add_argument("--skip-install", action="store_true", help="Skip first-time npm ci (layer rebuilding still requires Node.js)")
    args = parser.parse_args()
    try:
        rebuild(args.project, args.input_dir, args.reset_rig, not args.skip_install)
    except (OSError, ValueError, KeyError, TypeError, subprocess.CalledProcessError, cv2.error) as error:
        print(f"rebuild-mio: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
